FROM node:16-alpine

# workdir - usr/app for permission issues
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .
CMD [ "npm", "run", "start" ]

# jayampathi/docker/complex-client:latest