sudo: required
language: generic
services:
  - docker

# build all the images for tests
before_install:
  - docker build -t jayampathi/react-test -f ./client/Dockerfile.dev ./client

# run custom commands to run the tests
script:
  - docker run -e CI=true jayampathi/react-test npm run test

after_success:
  - docker build -t jayampthi/dockertest/multi-react-client ./client
  - docker build -t jayampthi/dockertest/multi-nginx ./nginx
  - docker build -t jayampthi/dockertest/multi-server ./server
  - docker build -t jayampthi/dockertest/mutli-worker ./worker
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jayampthi/dockertest/multi-react-client
  - docker push jayampthi/dockertest/multi-nginx
  - docker push jayampthi/dockertest/multi-server
  - docker push jayampthi/dockertest/multi-worker

# log into docker CLI

# push to docker hub
